import { AgentType } from '../types'

export const mockAgentThoughts: Record<AgentType, string[]> = {
  strategist: [
    'Analyzing market segments for Christian prayer apps...',
    'Identifying key differentiators from competitors',
    'Defining success metrics for launch week',
    "Creating user persona: 'Daily Devotion Seeker'",
    'Mapping customer journey from discovery to daily use',
    'Evaluating pricing strategies for premium features',
    '🤔 Should we focus on individual or church communities first?',
    'Calculating potential market size: 2.4B Christians globally',
  ],
  developer: [
    'Setting up Next.js project with TypeScript...',
    'Implementing Supabase authentication',
    'Optimizing landing page for Core Web Vitals',
    'Adding analytics tracking with Mixpanel',
    'Building responsive prayer timer component',
    'Implementing push notification system',
    '⚠️ Need decision: Firebase vs AWS for backend',
    'Deploying to Vercel with automatic previews',
  ],
  designer: [
    'Creating calming color palette with soft blues and golds',
    'Designing intuitive prayer tracking interface',
    'Sketching onboarding flow wireframes',
    'Building component library in Figma',
    'Testing accessibility with screen readers',
    'Creating micro-interactions for prayer completion',
    '📐 Considering card-based vs list-based layout',
    'Designing achievement badges for streak milestones',
  ],
  researcher: [
    'Surveying 150 potential users about prayer habits',
    'Analyzing competitor apps: Hallow, Pray.com, Abide',
    'Key insight: Users want guided prayer, not just tracking',
    'Testing landing page conversion: 2.3% baseline',
    'Identifying top user pain point: consistency',
    'Researching optimal notification timing',
    '💡 Discovery: Morning prayers have 3x engagement',
    'Documenting user feedback from beta testers',
  ],
  content: [
    'Writing landing page headline variations',
    'Creating 30-day content calendar',
    'Drafting welcome email sequence',
    'Writing App Store description (4.7 rating target)',
    'Developing social media templates',
    'Creating user testimonial campaigns',
    '✍️ Need input: Formal vs conversational tone?',
    'Preparing launch announcement for Christian blogs',
  ],
}
