/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDebugImport } from './routes/_authenticated/debug'
import { Route as errors500Import } from './routes/(errors)/500'
import { Route as errors404Import } from './routes/(errors)/404'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedGtmStudioRouteImport } from './routes/_authenticated/gtm-studio/route'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPrayerStudioIndexImport } from './routes/_authenticated/prayer-studio/index'
import { Route as AuthenticatedPrayerLabIndexImport } from './routes/_authenticated/prayer-lab/index'
import { Route as AuthenticatedOnboardingBuilderIndexImport } from './routes/_authenticated/onboarding-builder/index'
import { Route as AuthenticatedGtmStudioIndexImport } from './routes/_authenticated/gtm-studio/index'
import { Route as AuthenticatedFlowStudioIndexImport } from './routes/_authenticated/flow-studio/index'
import { Route as AuthenticatedClaudeAgentsIndexImport } from './routes/_authenticated/claude-agents/index'
import { Route as AuthenticatedAnalyticsIndexImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedSettingsNotificationsImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountImport } from './routes/_authenticated/settings/account'

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedDebugRoute = AuthenticatedDebugImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors500Route = errors500Import.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const errors404Route = errors404Import.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedGtmStudioRouteRoute =
  AuthenticatedGtmStudioRouteImport.update({
    id: '/gtm-studio',
    path: '/gtm-studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any,
)

const AuthenticatedPrayerStudioIndexRoute =
  AuthenticatedPrayerStudioIndexImport.update({
    id: '/prayer-studio/',
    path: '/prayer-studio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedPrayerLabIndexRoute =
  AuthenticatedPrayerLabIndexImport.update({
    id: '/prayer-lab/',
    path: '/prayer-lab/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedOnboardingBuilderIndexRoute =
  AuthenticatedOnboardingBuilderIndexImport.update({
    id: '/onboarding-builder/',
    path: '/onboarding-builder/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedGtmStudioIndexRoute =
  AuthenticatedGtmStudioIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGtmStudioRouteRoute,
  } as any)

const AuthenticatedFlowStudioIndexRoute =
  AuthenticatedFlowStudioIndexImport.update({
    id: '/flow-studio/',
    path: '/flow-studio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedClaudeAgentsIndexRoute =
  AuthenticatedClaudeAgentsIndexImport.update({
    id: '/claude-agents/',
    path: '/claude-agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/gtm-studio': {
      id: '/_authenticated/gtm-studio'
      path: '/gtm-studio'
      fullPath: '/gtm-studio'
      preLoaderRoute: typeof AuthenticatedGtmStudioRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500Import
      parentRoute: typeof rootRoute
    }
    '/_authenticated/debug': {
      id: '/_authenticated/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AuthenticatedDebugImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/claude-agents/': {
      id: '/_authenticated/claude-agents/'
      path: '/claude-agents'
      fullPath: '/claude-agents'
      preLoaderRoute: typeof AuthenticatedClaudeAgentsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/flow-studio/': {
      id: '/_authenticated/flow-studio/'
      path: '/flow-studio'
      fullPath: '/flow-studio'
      preLoaderRoute: typeof AuthenticatedFlowStudioIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/gtm-studio/': {
      id: '/_authenticated/gtm-studio/'
      path: '/'
      fullPath: '/gtm-studio/'
      preLoaderRoute: typeof AuthenticatedGtmStudioIndexImport
      parentRoute: typeof AuthenticatedGtmStudioRouteImport
    }
    '/_authenticated/onboarding-builder/': {
      id: '/_authenticated/onboarding-builder/'
      path: '/onboarding-builder'
      fullPath: '/onboarding-builder'
      preLoaderRoute: typeof AuthenticatedOnboardingBuilderIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/prayer-lab/': {
      id: '/_authenticated/prayer-lab/'
      path: '/prayer-lab'
      fullPath: '/prayer-lab'
      preLoaderRoute: typeof AuthenticatedPrayerLabIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/prayer-studio/': {
      id: '/_authenticated/prayer-studio/'
      path: '/prayer-studio'
      fullPath: '/prayer-studio'
      preLoaderRoute: typeof AuthenticatedPrayerStudioIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedGtmStudioRouteRouteChildren {
  AuthenticatedGtmStudioIndexRoute: typeof AuthenticatedGtmStudioIndexRoute
}

const AuthenticatedGtmStudioRouteRouteChildren: AuthenticatedGtmStudioRouteRouteChildren =
  {
    AuthenticatedGtmStudioIndexRoute: AuthenticatedGtmStudioIndexRoute,
  }

const AuthenticatedGtmStudioRouteRouteWithChildren =
  AuthenticatedGtmStudioRouteRoute._addFileChildren(
    AuthenticatedGtmStudioRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGtmStudioRouteRoute: typeof AuthenticatedGtmStudioRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDebugRoute: typeof AuthenticatedDebugRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedClaudeAgentsIndexRoute: typeof AuthenticatedClaudeAgentsIndexRoute
  AuthenticatedFlowStudioIndexRoute: typeof AuthenticatedFlowStudioIndexRoute
  AuthenticatedOnboardingBuilderIndexRoute: typeof AuthenticatedOnboardingBuilderIndexRoute
  AuthenticatedPrayerLabIndexRoute: typeof AuthenticatedPrayerLabIndexRoute
  AuthenticatedPrayerStudioIndexRoute: typeof AuthenticatedPrayerStudioIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGtmStudioRouteRoute:
    AuthenticatedGtmStudioRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDebugRoute: AuthenticatedDebugRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedClaudeAgentsIndexRoute: AuthenticatedClaudeAgentsIndexRoute,
  AuthenticatedFlowStudioIndexRoute: AuthenticatedFlowStudioIndexRoute,
  AuthenticatedOnboardingBuilderIndexRoute:
    AuthenticatedOnboardingBuilderIndexRoute,
  AuthenticatedPrayerLabIndexRoute: AuthenticatedPrayerLabIndexRoute,
  AuthenticatedPrayerStudioIndexRoute: AuthenticatedPrayerStudioIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/gtm-studio': typeof AuthenticatedGtmStudioRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/debug': typeof AuthenticatedDebugRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/claude-agents': typeof AuthenticatedClaudeAgentsIndexRoute
  '/flow-studio': typeof AuthenticatedFlowStudioIndexRoute
  '/gtm-studio/': typeof AuthenticatedGtmStudioIndexRoute
  '/onboarding-builder': typeof AuthenticatedOnboardingBuilderIndexRoute
  '/prayer-lab': typeof AuthenticatedPrayerLabIndexRoute
  '/prayer-studio': typeof AuthenticatedPrayerStudioIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}

export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/debug': typeof AuthenticatedDebugRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/claude-agents': typeof AuthenticatedClaudeAgentsIndexRoute
  '/flow-studio': typeof AuthenticatedFlowStudioIndexRoute
  '/gtm-studio': typeof AuthenticatedGtmStudioIndexRoute
  '/onboarding-builder': typeof AuthenticatedOnboardingBuilderIndexRoute
  '/prayer-lab': typeof AuthenticatedPrayerLabIndexRoute
  '/prayer-studio': typeof AuthenticatedPrayerStudioIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/gtm-studio': typeof AuthenticatedGtmStudioRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/_authenticated/debug': typeof AuthenticatedDebugRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/claude-agents/': typeof AuthenticatedClaudeAgentsIndexRoute
  '/_authenticated/flow-studio/': typeof AuthenticatedFlowStudioIndexRoute
  '/_authenticated/gtm-studio/': typeof AuthenticatedGtmStudioIndexRoute
  '/_authenticated/onboarding-builder/': typeof AuthenticatedOnboardingBuilderIndexRoute
  '/_authenticated/prayer-lab/': typeof AuthenticatedPrayerLabIndexRoute
  '/_authenticated/prayer-studio/': typeof AuthenticatedPrayerStudioIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/gtm-studio'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/404'
    | '/500'
    | '/debug'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/analytics'
    | '/claude-agents'
    | '/flow-studio'
    | '/gtm-studio/'
    | '/onboarding-builder'
    | '/prayer-lab'
    | '/prayer-studio'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/404'
    | '/500'
    | '/debug'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/analytics'
    | '/claude-agents'
    | '/flow-studio'
    | '/gtm-studio'
    | '/onboarding-builder'
    | '/prayer-lab'
    | '/prayer-studio'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/gtm-studio'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/_authenticated/debug'
    | '/_authenticated/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/analytics/'
    | '/_authenticated/claude-agents/'
    | '/_authenticated/flow-studio/'
    | '/_authenticated/gtm-studio/'
    | '/_authenticated/onboarding-builder/'
    | '/_authenticated/prayer-lab/'
    | '/_authenticated/prayer-studio/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/sign-in",
        "/(auth)/sign-up",
        "/(errors)/404",
        "/(errors)/500"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/gtm-studio",
        "/_authenticated/settings",
        "/_authenticated/debug",
        "/_authenticated/",
        "/_authenticated/analytics/",
        "/_authenticated/claude-agents/",
        "/_authenticated/flow-studio/",
        "/_authenticated/onboarding-builder/",
        "/_authenticated/prayer-lab/",
        "/_authenticated/prayer-studio/"
      ]
    },
    "/_authenticated/gtm-studio": {
      "filePath": "_authenticated/gtm-studio/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/gtm-studio/"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.tsx"
    },
    "/_authenticated/debug": {
      "filePath": "_authenticated/debug.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/analytics/": {
      "filePath": "_authenticated/analytics/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/claude-agents/": {
      "filePath": "_authenticated/claude-agents/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/flow-studio/": {
      "filePath": "_authenticated/flow-studio/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/gtm-studio/": {
      "filePath": "_authenticated/gtm-studio/index.tsx",
      "parent": "/_authenticated/gtm-studio"
    },
    "/_authenticated/onboarding-builder/": {
      "filePath": "_authenticated/onboarding-builder/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/prayer-lab/": {
      "filePath": "_authenticated/prayer-lab/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/prayer-studio/": {
      "filePath": "_authenticated/prayer-studio/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated/settings"
    }
  }
}
ROUTE_MANIFEST_END */
